include:
- ./functions/sudodataexporter.zip
kind: ArchiveUploadSpec
name: functions-sudodataexporter-zip-368z

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sudodataexporter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-sudodataexporter-zip-368z
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T08:18:05Z"
