include:
- ./functions/bpdataexporter.zip
kind: ArchiveUploadSpec
name: functions-bpdataexporter-zip-lYy3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bpdataexporter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-bpdataexporter-zip-lYy3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-17T08:24:38Z"
