include:
- ./functions/lidataexporter.zip
kind: ArchiveUploadSpec
name: functions-lidataexporter-zip-ytK1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: lidataexporter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-lidataexporter-zip-ytK1
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T05:37:32Z"
