include:
- ./functions/radataexporter.zip
kind: ArchiveUploadSpec
name: functions-radataexporter-zip-dHXd

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: radataexporter
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-radataexporter-zip-dHXd
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T03:00:59Z"
