apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: bpdataexporter
spec:
  createingress: true
  functionref:
    functionweights: null
    name: bpdataexporter
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /bpdataexporter
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /bpdataexporter
